"""Pydantic schemas shared between Kolibri service routes."""
from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field

__all__ = [
    "HealthResponse",
    "InferenceRequest",
    "InferenceResponse",
    "SAMLLoginResponse",
]


class HealthResponse(BaseModel):
    status: str = "ok"
    response_mode: str
    sso_enabled: bool
    prometheus_namespace: str


class InferenceRequest(BaseModel):
    prompt: str = Field(min_length=1, description="User prompt that should be answered by the model")
    mode: Optional[str] = Field(default=None, description="Frontend-selected response mode")
    temperature: Optional[float] = Field(default=None, ge=0.0, le=2.0)
    max_tokens: Optional[int] = Field(default=None, ge=1)


class InferenceResponse(BaseModel):
    response: str = Field(description="Text generated by the LLM")
    provider: str = Field(description="Identifier of the upstream provider")
    latency_ms: Optional[float] = Field(default=None, description="End-to-end latency for the upstream call")


class SAMLLoginResponse(BaseModel):
    token: str
    subject: str
    expires_at: Optional[float]
    relay_state: Optional[str]
