{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kolibri-enterprise.fullname" . }}
  labels:
    {{- include "kolibri-enterprise.labels" . | nindent 4 }}
{{- end }}
