global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: kolibri-knowledge
    metrics_path: /metrics
    static_configs:
      - targets:
          - kolibri-backend:8000

  - job_name: kolibri-node
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://kolibri-backend:8000/healthz
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

rule_files: []
