name: Kolibri CI

on:
  push:
    branches: [ main, work ]
  pull_request:
  schedule:
    - cron: '0 3 * * *'

jobs:
  python-quality:
    name: Python lint & tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Установка Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip
      - name: Установка инструментов
        run: |
          python -m pip install --upgrade pip
          python -m pip install ruff pyright pytest coverage
      - name: Ruff
        run: ruff check .
      - name: Pyright
        run: pyright
      - name: Pytest
        run: pytest -q

  core-build:
    name: CMake, тесты и ISO
    runs-on: ubuntu-latest
    needs: python-quality
    steps:
      - uses: actions/checkout@v4
      - name: Установка зависимостей C/ISO
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake nasm grub-pc-bin xorriso gcc-multilib
      - name: Конфигурация CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
      - name: Сборка C-ядра
        run: cmake --build build -j
      - name: Юнит-тесты C
        run: ctest --test-dir build --output-on-failure
      - name: Сборка ISO
        run: ./scripts/build_iso.sh
      - name: Публикация артефакта ISO
        uses: actions/upload-artifact@v4
        with:
          name: kolibri-iso
          path: build/kolibri.iso

  wasm-build:
    name: WebAssembly
    runs-on: ubuntu-latest
    needs: core-build
    steps:
      - uses: actions/checkout@v4
      - name: Установка Emscripten
        uses: mymindstorm/setup-emsdk@v13
        with:
          emsdk-version: latest
      - name: Конфигурация CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
      - name: Сборка kolibri.wasm
        run: cmake --build build --target kolibri_wasm
      - name: Публикация артефактов WASM
        uses: actions/upload-artifact@v4
        with:
          name: kolibri-wasm
          path: |
            build/wasm/kolibri.wasm
            build/wasm/kolibri.wasm.sha256
            build/wasm/kolibri.wasm.txt
