name: Kolibri CI

on:
  push:
    branches: [ main, work ]
  pull_request:
  schedule:
    - cron: '0 3 * * *'

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10', '3.11', '3.12' ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install ruff
      - name: Ruff lint
        run: ruff check .

  typecheck:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        python-version: [ '3.10', '3.11', '3.12' ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyright
      - name: Pyright
        run: pyright

  test:
    runs-on: ubuntu-latest
    needs: typecheck
    strategy:
      matrix:
        python-version: [ '3.10', '3.11', '3.12' ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
      - name: Run pytest
        run: pytest -q

  coverage:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip
      - name: Install coverage dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install coverage pytest
      - name: Run coverage
        run: |
          coverage run -m pytest -q
          coverage xml
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
