name: Deploy frontend to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: pages
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build frontend
    runs-on: ubuntu-latest
    env:
      PAGES_ARTIFACT_NAME: github-pages-${{ github.run_id }}-${{ github.run_attempt }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Determine public base URL
        run: |
          if [ -s CNAME ]; then
            echo "KOLIBRI_PUBLIC_BASE_URL=/" >> "$GITHUB_ENV"
            echo "Using root base URL because CNAME is present"
          else
            echo "KOLIBRI_PUBLIC_BASE_URL=/${GITHUB_REPOSITORY#*/}/" >> "$GITHUB_ENV"
            echo "Using repository base URL /${GITHUB_REPOSITORY#*/}/"
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Build Kolibri WebAssembly
        run: KOLIBRI_WASM_ALLOW_STUB_SUCCESS=1 ./scripts/build_wasm.sh

      - name: Build frontend
        working-directory: frontend
        run: KOLIBRI_ALLOW_WASM_STUB=1 npm run build

      - name: Copy CNAME
        run: cp CNAME frontend/dist/CNAME

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: ${{ env.PAGES_ARTIFACT_NAME }}
          path: frontend/dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    env:
      PAGES_ARTIFACT_NAME: github-pages-${{ github.run_id }}-${{ github.run_attempt }}

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: ${{ env.PAGES_ARTIFACT_NAME }}
