name: Kolibri Nightly Fuzz

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  fuzz-nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Clang & deps
        run: |
          sudo apt-get update
          sudo apt-get install -y clang lld cmake ninja-build libsqlite3-dev libssl-dev
      - name: Configure fuzz target
        run: cmake -S . -B build-fuzz -DCMAKE_BUILD_TYPE=RelWithDebInfo -DKOLIBRI_ENABLE_FUZZ=ON -DCMAKE_C_COMPILER=clang
      - name: Build fuzz target
        run: cmake --build build-fuzz --target kolibri_fuzz_script -j
      - name: Run fuzzing session
        run: |
          ./build-fuzz/kolibri_fuzz_script -max_total_time=600 -jobs=2 -workers=2 || true
      - name: Archive fuzz corpus
        uses: actions/upload-artifact@v4
        with:
          name: fuzz-corpus
          path: build-fuzz
          retention-days: 7
